name: MovingWall
author: Jethro
main: me.jethro.movingwall.MovingWall
version: 1.0
api-version: 1.20


commands:
  wall:
    description: Start or stop the creation of a big wall
    usage: /wall start