name: AnimalKiller
author: Jethro
main: me.jethro.animalkiller.AnimalKiller
version: 1.0
api-version: 1.20


commands:
  start:
    description: Starts the Animal Killer game
    usage: /start
  reset:
    description: Resets the game
    usage: /reset